# FRONTEND
# Obtener el index.html del proyecto
GET http://localhost:9000

###
# Peticion prueba a Google
GET https://www.google.com/

### -*******************************************************************************-
@host = http://localhost:4000
###
# API
# Obtener los roles (Prueba)
GET {{host}}/userRoles


### -*********************************************************-
# USERS routes
# Get all users
GET {{host}}/users

###

# Register user
POST {{host}}/users
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": "",
  "userRoleId": ""
}

### -*********************************************************-
# flightS routes
# Get all flights

GET {{host}}/flights

###
# Edit a flight
PATCH {{host}}/flights/12
Content-Type: application/json

{
      "id": "1",
      "number": "1",
      "origin": "mexico",
      "destination":cancun,
      "departure":"",
      "arrival": "",
      "capacity": 10,
}